### PR TITLE
Remove deprecated ModMenu API

### LINKED ISSUE #93: Deprecated ModMenu Stuff
This is put in logs:

`[main/WARN]: WARNING! Mod cloth-config2 is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

`[main/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
- Removes log warn
- Supports new API
- Properly fixes #93

### CODE REVIEW

**Comment by shedaniel** [comment]
Not how it works, you are supposed to add badges https://github.com/TerraformersMC/ModMenu/wiki/API

**Comment by DragonEggBedrockBreaking** [comment]
Badges are only for library/deprecated. API and clientsideonly have been removed.

**Comment by shedaniel** [comment]
This is a library.

**Comment by DragonEggBedrockBreaking** [comment]
Ok, I will add the library badge, give me a few mins.

**Comment by DragonEggBedrockBreaking** [comment]
Done here

**Pull request merged**
